// Poses do mascote. Cada pose e um bloco de texto, um caractere por celula
// (design D5): ajustar a animacao e trocar um caractere, nao reexportar asset.
//
//   .  vazio      O  laranja do corpo    K  preto (olhos)
//   G  verde (v)  P  roxo (?)            W  branco
//
// Corpo: 15 colunas x 12 linhas. Simbolos: 6 x 7.
// Toda pose DEVE respeitar essas dimensoes — check.py verifica.

const GRID = { w: 15, h: 12, sw: 6, sh: 7 };

const POSES = {
  // Vista frontal, bracos na lateral, olhos abertos.
  front: `
...............
...............
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..OKKKOOOKKKO..
.OOKKKOOOKKKOO.
.OOOOOOOOOOOOO.
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..O.O.....O.O..
..O.O.....O.O..
`,

  // Olhos apertados: so a linha de baixo. E a piscada.
  front_blink: `
...............
...............
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..OOOOOOOOOOO..
.OOKKKOOOKKKOO.
.OOOOOOOOOOOOO.
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..O.O.....O.O..
..O.O.....O.O..
`,

  // Olhos felizes fechados: dois arcos ^ ^.
  front_happy: `
...............
...............
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..OOKOOOOOKOO..
.OOKKKOOOKKKOO.
.OOOOOOOOOOOOO.
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..O.O.....O.O..
..O.O.....O.O..
`,

  // Piscadinha: um olho aberto, outro em arco.
  front_wink: `
...............
...............
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..OKKKOOOOKOO..
.OOKKKOOOKKKOO.
.OOOOOOOOOOOOO.
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..O.O.....O.O..
..O.O.....O.O..
`,

  // Bracos levantados acima da cabeca (chamando atencao / comemorando).
  front_up: `
.O...........O.
.O...........O.
.OOOOOOOOOOOOO.
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..OKKKOOOKKKO..
..OKKKOOOKKKO..
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..O.O.....O.O..
..O.O.....O.O..
`,

  front_up_happy: `
.O...........O.
.O...........O.
.OOOOOOOOOOOOO.
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..OOKOOOOOKOO..
..OKKKOOOKKKO..
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..O.O.....O.O..
..O.O.....O.O..
`,

  // Aceno: um braco pra cima, o outro na lateral. Alternando os dois da o
  // tchauzinho de verdade — o front_up sozinho lia como bicho parado de bracos
  // pra cima, nao como alguem acenando.
  front_wave_a: `
.O.............
.O.............
.OOOOOOOOOOOO..
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..OKKKOOOKKKO..
..OKKKOOOKKKOO.
..OOOOOOOOOOOO.
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..O.O.....O.O..
..O.O.....O.O..
`,

  front_wave_b: `
.............O.
.............O.
..OOOOOOOOOOOO.
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..OKKKOOOKKKO..
.OOKKKOOOKKKO..
.OOOOOOOOOOOO..
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..O.O.....O.O..
..O.O.....O.O..
`,

  // Olhos de 3x3: arregalado, pedindo socorro.
  front_wide: `
...............
...............
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..OKKKOOOKKKO..
..OKKKOOOKKKO..
.OOKKKOOOKKKOO.
.OOOOOOOOOOOOO.
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..O.O.....O.O..
..O.O.....O.O..
`,

  // Sobrancelha grossa atravessando o rosto: impaciente, esperando resposta.
  front_brow: `
...............
...............
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..KKKKKKKKKKK..
.OOKKKOOOKKKOO.
.OOOOOOOOOOOOO.
..OOOOOOOOOOO..
..OOOOOOOOOOO..
..O.O.....O.O..
..O.O.....O.O..
`,

  // Achatado e mais largo: o susto de quem levou um clique.
  front_squash: `
...............
...............
...............
...............
.OOOOOOOOOOOOO.
.OOKKKOOOKKKOO.
.OOKKKOOOKKKOO.
.OOOOOOOOOOOOO.
.OOOOOOOOOOOOO.
.OOOOOOOOOOOOO.
..O.O.....O.O..
..O.O.....O.O..
`,

  // Vista lateral com focinho, quadro A do ciclo de caminhada.
  side_a: `
...............
...............
....OOOOOOOO...
....OOOOOOOO...
....OKOOKOOO...
....OKOOKOOO...
..OOOOOOOOOO...
..OOOOOOOOOO...
....OOOOOOOO...
....OOOOOOOO...
....O.O..O.O...
....O....O.....
`,

  // Quadro B: as outras duas patas apoiam.
  side_b: `
...............
...............
....OOOOOOOO...
....OOOOOOOO...
....OKOOKOOO...
....OKOOKOOO...
..OOOOOOOOOO...
..OOOOOOOOOO...
....OOOOOOOO...
....OOOOOOOO...
....O.O..O.O...
......O....O...
`,
};

// Simbolo acima da cabeca. E ele que chama a atencao de longe — o corpo
// laranja de 70px nao e pego pela visao periferica numa tela de 5360px (D11).
const SYMBOLS = {
  q: `
.PPP..
P...P.
....P.
...P..
..P...
......
..P...
`,

  bulb_on: `
..YY..
.YYYY.
.YYYY.
.YYYY.
..YY..
..AA..
..AA..
`,

  bulb_off: `
..AA..
.AAAA.
.AAAA.
.AAAA.
..AA..
..AA..
..AA..
`,

  heart: `
.RR.RR
RRRRRR
RRRRRR
.RRRR.
..RR..
......
......
`,

  // O check se desenha em tres quadros.
  c1: `
......
......
......
......
......
G.....
.G....
`,

  c2: `
......
......
......
......
...G..
G.G...
.G....
`,

  c3: `
......
......
.....G
....G.
...G..
G.G...
.G....
`,
};

// Camada de adereco, desenhada por cima do corpo e alinhada com ele. Assim uma
// variacao nova nao exige redesenhar as 12 poses do corpo.
const PROPS = {
  // Cada adereco tem versao de frente e de perfil. O motor escolhe pela pose,
  // e aplica em TODOS os quadros da sequencia — inclusive na entrada e na
  // saida andando. Sem isso o objeto pisca: aparece quando ele vira de frente
  // e some quando vira de lado.
  headphones: `
...............
....BBBBBBB....
..BB.......BB..
.BBB.......BBB.
.BBB.......BBB.
.BB.........BB.
...............
...............
...............
...............
...............
...............
`,

  headphones_side: `
...............
.....BBBBBB....
....B......B...
....BB....BB...
....BB....BB...
....B......B...
...............
...............
...............
...............
...............
...............
`,

  // Capacete + martelo erguido.
  work_a: `
...............
.....YYYYY.....
...YYYYYYYYY...
..YYYYYYYYYYY..
...............
...........AAA.
...........AAA.
............K..
............K..
............K..
...............
...............
`,

  // Mesmo capacete, martelo descendo.
  work_b: `
...............
.....YYYYY.....
...YYYYYYYYY...
..YYYYYYYYYYY..
............K..
............K..
...........AAA.
...........AAA.
...............
...............
...............
...............
`,

  work_side: `
...............
.....YYYYY.....
....YYYYYYY....
...YYYYYYYYY...
...............
...........AAA.
...........AAA.
............K..
............K..
............K..
...............
...............
`,

  // Xicara branca com cafe escuro e alca, vapor subindo. Dois quadros: so o
  // vapor se mexe — o braco que segura a xicara nao pode mudar de pose.
  // Xicara: colunas 12-14, fora das colunas dos olhos (9-11), com a alca na
  // altura do braco. Cafe escuro no topo, base escura embaixo — branco puro sem
  // borda lia como um buraco no corpo, nao como um objeto.
  // O braco que a segura nao muda de pose em nenhum quadro: quem anima e o vapor.
  mug_a: `
...............
...............
...............
...............
.............W.
............W..
............KKK
...........KWWW
...........KWWW
............KKK
...............
...............
`,

  mug_b: `
...............
...............
.............W.
............W..
...............
............W..
............KKK
...........KWWW
...........KWWW
............KKK
...............
...............
`,

  mug_side: `
...............
...............
...............
...............
.............W.
............W..
............KKK
............WWW
............WWW
............KKK
...............
...............
`,




  // Passarinho pousado no lombo. Dois quadros: ele se ajeita.
  bird_a: `
...............
...............
............BB.
...........BWBK
............BB.
...............
...............
...............
...............
...............
...............
...............
`,

  bird_b: `
...............
............BB.
...........BWBK
............BB.
...............
...............
...............
...............
...............
...............
...............
...............
`,

  bird_side: `
..........BB...
.........BWBK..
..........BB...
...............
...............
...............
...............
...............
...............
...............
...............
...............
`,

  // Varinha de faiscas, dois quadros de estalo.
  wand_a: `
...............
...............
...............
..............Y
............Y.Y
..........KKKKY
............Y.Y
..............Y
...............
...............
...............
...............
`,

  wand_b: `
...............
...............
..............Y
...............
.............Y.
..........KKKK.
.............Y.
...............
..............Y
...............
...............
...............
`,
};
